# SPDX-License-Identifier: AGPL-3.0-or-later
"""Deterministic export of a champion, rig or library (10 §8.3).

Writes `<out_dir>/<id>.glb` (one skinned mesh plus prop meshes, vertex colors, material-slot
names, every stashed action sampled at 30 fps, no images, no normals or UVs: shading is faceted
from screen-space derivatives) and `<out_dir>/<id>.anims.ron`, the marker sidecar.
"""

import os

import bpy

from . import clips, glb, rig


def find_armature():
    arms = [o for o in bpy.context.scene.objects if o.type == "ARMATURE" and o.get("mftr_archetype")]
    if len(arms) != 1:
        raise RuntimeError(f"expected exactly one MFTR armature in the scene, found {len(arms)}")
    return arms[0]


def stashed_actions(armature):
    """The clips that ship: one NLA track per action, in name order."""
    ad = armature.animation_data
    if not ad:
        return []
    acts = {s.action for t in ad.nla_tracks for s in t.strips if s.action}
    return sorted(acts, key=lambda a: a.name)


def export(out_dir, pack_id, kind):
    """Export the scene's MFTR armature and its meshes. `kind`: champion, library or rig."""
    scene = bpy.context.scene
    scene.render.fps = clips.FPS
    scene.render.fps_base = 1.0
    arm = find_armature()
    if arm.animation_data:
        arm.animation_data.action = None
    clips.reset_pose(arm)

    meshes = [o for o in scene.objects if o.type == "MESH" and o.parent == arm]
    for o in scene.objects:
        o.select_set(False)
    for o in [arm] + meshes:
        o.hide_set(False)
        o.select_set(True)
    bpy.context.view_layer.objects.active = arm

    os.makedirs(out_dir, exist_ok=True)
    path = os.path.join(out_dir, f"{pack_id}.glb")
    bpy.ops.export_scene.gltf(
        filepath=path,
        export_format="GLB",
        use_selection=True,
        export_yup=True,
        export_apply=False,
        export_texcoords=False,
        export_normals=False,
        export_tangents=False,
        export_vertex_color="ACTIVE",
        export_all_vertex_colors=False,
        export_materials="EXPORT",
        export_image_format="NONE",
        export_cameras=False,
        export_lights=False,
        export_extras=False,
        export_morph=False,
        export_skins=True,
        export_def_bones=False,
        export_influence_nb=4,
        export_leaf_bone=False,
        export_rest_position_armature=True,
        export_animations=kind != "rig",
        export_animation_mode="ACTIONS",
        export_force_sampling=True,
        export_frame_step=1,
        export_optimize_animation_size=True,
        export_reset_pose_bones=True,
        export_anim_slide_to_zero=False,
        export_negative_frame="SLIDE",
        will_save_settings=False,
    )
    stats = glb.process(path)
    sidecar = os.path.join(out_dir, f"{pack_id}.anims.ron")
    with open(sidecar, "w", encoding="utf-8", newline="\n") as f:
        f.write(sidecar_text(arm, pack_id, kind))
    return {"glb": path, "sidecar": sidecar, "bytes": os.path.getsize(path), **stats}


def _ron_str(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def sidecar_text(arm, pack_id, kind):
    lines = [
        "// Generated by tools/blender/mftr_blender (export). Do not edit: change the .blend and re-export.",
        "(",
        f"    id: {_ron_str(pack_id)},",
        f"    kind: {_ron_str(kind)},",
        f"    archetype: {_ron_str(arm.get('mftr_archetype', rig.ARCHETYPE))},",
        f"    rig_version: {int(arm.get('mftr_rig_version', rig.VERSION))},",
        f"    fps: {clips.FPS},",
        "    clips: [",
    ]
    for act in (stashed_actions(arm) if kind != "rig" else []):
        start, end = act.frame_range
        frames = int(round(end - start))
        stride = act.get("mftr_stride_speed")
        markers = sorted(((m.name, int(m.frame - start)) for m in act.pose_markers), key=lambda m: (m[1], m[0]))
        marker_text = ", ".join(f"(name: {_ron_str(n)}, frame: {f})" for n, f in markers)
        lines.append(
            f"        (name: {_ron_str(act.name)}, frames: {frames}, looping: {'true' if act.get('mftr_loop') else 'false'}, "
            f"layer: {_ron_str(act.get('mftr_layer', 'full'))}, "
            f"stride_speed: {format(float(stride), '.1f') if stride is not None else 'None'}, markers: [{marker_text}]),"
        )
    lines += ["    ],", ")", ""]
    return "\n".join(lines)
